import Head from "next/head";
// import Image from "next/image";
// import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title className={styles.title}>Hunter coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hunter coder</h1>
        <div className={styles.wrapper}>
          {/* <Image
            className={styles.homeimg}
            src="/home.webp"
            alt=""
            width={232}
            height={160}
          /> */}
          <img
            className={styles.homeimg}
            src="/home.webp"
            alt="Hunting coder"
            width={232}
            height={160}
          />
        </div>
        <h2>&lt; Hunting coder/&gt;</h2>
        <div className={styles.blogs}>
          <div className="blog">
            <h3>React Js</h3>
            <p>
              Learn react js through following code with harry courses in 2022
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Consequatur quibusdam eaque sunt.
            </p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className="blog">
            <h3>React Js</h3>
            <p>
              Learn react js through following code with harry courses in 2022
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Consequatur quibusdam eaque sunt.
            </p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className="blog">
            <h3>React Js</h3>
            <p>
              Learn react js through following code with harry courses in 2022
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Consequatur quibusdam eaque sunt.
            </p>
            <button className={styles.btn}>Read More</button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
